### ISSUE TITLE
Shows write_mlv instead of raw2mlv as arguments.

### ISSUE THREAD

**Issue by cmhamiche** [ilia3101/LibMLV#1]
This is a small detail but it might confuse some "early adopters".
https://github.com/ilia3101/LibMLV/blob/master/raw2mlv/raw2mlv.c 
line 56 
It shows write_mlv instead of raw2mlv in arguments.
![Sans titre](https://user-images.githubusercontent.com/32405217/68625896-7cb77180-04da-11ea-8b2b-1f7f389ea4dc.jpg)

**Comment by ilia3101** [comment]
Thank you for pointing this out. That was the original name, forgot to change it there.

I will do this tomorrow.

**Comment by ilia3101** [comment]
https://github.com/ilia3101/LibMLV/commit/6570f1503034bdd4fd2e9094a1ae973b29ace858
